services:
  postgres:
    container_name: ch_postgres
    image: postgres:15-alpine
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: '"conference-hall","conference-hall-test"'
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    container_name: ch_redis
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'

  firebase-emulators:
    container_name: ch_firebase_emulators
    image: us-docker.pkg.dev/firebase-cli/us/firebase
    platform: linux/amd64
    working_dir: /workspace
    command: ['--project=conference-hall', 'emulators:start', '--only', 'auth,storage', '--import', 'fixtures']
    volumes:
      - ./docker/firebase/firebase.json:/workspace/firebase.json:ro
      - ./docker/firebase/storage.rules:/workspace/storage.rules:ro
      - ./docker/firebase/fixtures:/workspace/fixtures:ro
    ports:
      - '9099:9099'
      - '9199:9199'
      - '4000:4000'

  mailpit:
    container_name: ch_mailpit
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
