minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - better-auth
  - '@better-auth/*'

allowBuilds:
  '@prisma/engines': false
  core-js: false
  esbuild: false
  lefthook: false
  msgpackr-extract: false
  prisma: false
