export const SESSION_COLORS = [
  {
    name: 'Stone',
    value: 'stone',
    color: 'text-stone-500',
    block: 'text-stone-600 bg-stone-50 border border-stone-300',
  },
  {
    name: 'Pink',
    value: 'pink',
    color: 'text-pink-500',
    block: 'text-pink-600 bg-pink-50 border border-pink-300',
  },
  {
    name: 'Purple',
    value: 'purple',
    color: 'text-purple-500',
    block: 'text-purple-600 bg-purple-50 border border-purple-300',
  },
  {
    name: 'Blue',
    value: 'blue',
    color: 'text-blue-500',
    block: 'text-blue-600 bg-blue-50 border border-blue-300',
  },
  {
    name: 'Teal',
    value: 'teal',
    color: 'text-teal-500',
    block: 'text-teal-600 bg-teal-50 border border-teal-300',
  },
  {
    name: 'Green',
    value: 'green',
    color: 'text-green-500',
    block: 'text-green-600 bg-green-50 border border-green-300',
  },
  {
    name: 'Yellow',
    value: 'yellow',
    color: 'text-yellow-500',
    block: 'text-yellow-600 bg-yellow-50 border border-yellow-300',
  },
  {
    name: 'Red',
    value: 'red',
    color: 'text-red-500',
    block: 'text-red-600 bg-red-50 border border-red-300',
  },
];

export const SESSION_EMOJIS = [
  { code: 'book', skin: '📚', name: 'Book' },
  { code: 'clock', skin: '🕒', name: 'Clock' },
  { code: 'bar_chart', skin: '📊', name: 'Bar Chart' },
  { code: 'briefcase', skin: '💼', name: 'Briefcase' },
  { code: 'speech_balloon', skin: '💬', name: 'Speech Balloon' },
  { code: 'link', skin: '🔗', name: 'Link' },
  { code: 'chart_with_upwards_trend', skin: '📈', name: 'Chart' },
  { code: 'wrench', skin: '🛠️', name: 'Wrench' },
  { code: 'brain', skin: '🧠', name: 'Brain' },
  { code: 'clipboard', skin: '📋', name: 'Clipboard' },
  { code: 'round_pushpin', skin: '📍', name: 'Round Pushpin' },
  { code: 'microphone', skin: '🎤', name: 'Microphone' },
  { code: 'movie_camera', skin: '🎥', name: 'Movie Camera' },
  { code: 'globe_with_meridians', skin: '🌐', name: 'Globe' },
  { code: 'art', skin: '🎨', name: 'Artist Palette' },
  { code: 'man_technologist', skin: '🧑‍💻', name: 'Man Technologist' },
  { code: 'woman_technologist', skin: '👩‍💻', name: 'Woman Technologist' },
  { code: 'trophy', skin: '🏆', name: 'Trophy' },
  { code: 'rocket', skin: '🚀', name: 'Rocket' },
  { code: 'light_bulb', skin: '💡', name: 'Light Bulb' },
  { code: 'question', skin: '❓', name: 'Question Mark' },
  { code: 'heart', skin: '❤️', name: 'Heart' },
  { code: 'green_circle', skin: '🟢', name: 'Green Circle' },
  { code: 'orange_circle', skin: '🟠', name: 'Orange Circle' },
  { code: 'red_circle', skin: '🔴', name: 'Red Circle' },
];
