export const SESSION_EMOJIS = [
  { code: 'book', skin: '📚', name: 'Book' },
  { code: 'clock', skin: '🕒', name: 'Clock' },
  { code: 'bar_chart', skin: '📊', name: 'Bar Chart' },
  { code: 'briefcase', skin: '💼', name: 'Briefcase' },
  { code: 'speech_balloon', skin: '💬', name: 'Speech Balloon' },
  { code: 'link', skin: '🔗', name: 'Link' },
  { code: 'chart_with_upwards_trend', skin: '📈', name: 'Chart' },
  { code: 'wrench', skin: '🛠️', name: 'Wrench' },
  { code: 'brain', skin: '🧠', name: 'Brain' },
  { code: 'clipboard', skin: '📋', name: 'Clipboard' },
  { code: 'round_pushpin', skin: '📍', name: 'Round Pushpin' },
  { code: 'microphone', skin: '🎤', name: 'Microphone' },
  { code: 'movie_camera', skin: '🎥', name: 'Movie Camera' },
  { code: 'globe_with_meridians', skin: '🌐', name: 'Globe' },
  { code: 'art', skin: '🎨', name: 'Artist Palette' },
  { code: 'man_technologist', skin: '🧑‍💻', name: 'Man Technologist' },
  { code: 'woman_technologist', skin: '👩‍💻', name: 'Woman Technologist' },
  { code: 'trophy', skin: '🏆', name: 'Trophy' },
  { code: 'rocket', skin: '🚀', name: 'Rocket' },
  { code: 'light_bulb', skin: '💡', name: 'Light Bulb' },
  { code: 'question', skin: '❓', name: 'Question Mark' },
  { code: 'heart', skin: '❤️', name: 'Heart' },
  { code: 'green_circle', skin: '🟢', name: 'Green Circle' },
  { code: 'orange_circle', skin: '🟠', name: 'Orange Circle' },
  { code: 'red_circle', skin: '🔴', name: 'Red Circle' },
];
