import fastifyHelmet from '@fastify/helmet';
import type { FastifyInstance } from 'fastify';
import { getSharedServerEnv } from '../environment.server.ts';

const { NODE_ENV, APP_URL } = getSharedServerEnv();

const isProduction = NODE_ENV === 'production';

// Security-related HTTP response headers with Helmet.
// The CSP is report-only, with per-request nonces generated by @fastify/helmet
// and automatically appended to `script-src` and `style-src`.
export async function applySecurity(app: FastifyInstance) {
  await app.register(fastifyHelmet, {
    enableCSPNonces: true,
    referrerPolicy: { policy: 'same-origin' },
    crossOriginEmbedderPolicy: false,
    contentSecurityPolicy: {
      reportOnly: true,
      directives: {
        'connect-src': [
          !isProduction ? 'ws://localhost:*' : '',
          !isProduction ? 'http://localhost:*' : '',
          isProduction ? '*.googleapis.com' : '',
          "'self'",
        ].filter(Boolean),
        'frame-src': ["'self'", 'https://challenges.cloudflare.com', !isProduction ? 'http://localhost:*' : ''].filter(
          Boolean,
        ),
        'font-src': ["'self'", 'data:'],
        'img-src': ["'self'", 'data:', 'https:'],
        'script-src': [
          "'strict-dynamic'",
          "'unsafe-eval'",
          "'self'",
          isProduction ? `${APP_URL}/__/auth/*` : '',
          isProduction ? `${APP_URL}/cdn-cgi/*` : '',
          'https://challenges.cloudflare.com',
        ].filter(Boolean),
        // Nonces are never applied to attributes, so a nonce-only directive would be a
        // no-op: drop Helmet's default `script-src-attr 'none'` entirely.
        'script-src-attr': null,
        // Helmet defaults, kept explicit so the auto-appended nonce extends them
        // instead of replacing them.
        'style-src': ["'self'", 'https:', "'unsafe-inline'"],
        'upgrade-insecure-requests': null,
      },
    },
  });
}
