import fastifyHelmet from '@fastify/helmet';
import type { FastifyInstance } from 'fastify';
import { getSharedServerEnv } from '../environment.server.ts';

const { NODE_ENV } = getSharedServerEnv();

const isProduction = NODE_ENV === 'production';

// Security-related HTTP response headers with Helmet.
// The CSP is report-only, with per-request nonces generated by @fastify/helmet.
// Note: with 'strict-dynamic', host-source allowlists in script-src are ignored by
// modern browsers — only the nonce (and scripts it loads) are trusted.
export async function applySecurity(app: FastifyInstance) {
  await app.register(fastifyHelmet, {
    enableCSPNonces: true,
    referrerPolicy: { policy: 'same-origin' },
    crossOriginEmbedderPolicy: false,
    contentSecurityPolicy: {
      reportOnly: true,
      directives: {
        'default-src': ["'self'"],
        'base-uri': ["'self'"],
        'object-src': ["'none'"],
        'form-action': ["'self'"],
        'frame-ancestors': ["'self'"],
        'connect-src': isProduction ? ["'self'"] : ['ws://localhost:*', 'http://localhost:*', "'self'"],
        'frame-src': isProduction
          ? ["'self'", 'https://challenges.cloudflare.com']
          : ["'self'", 'https://challenges.cloudflare.com', 'http://localhost:*'],
        'font-src': ["'self'", 'data:'],
        'img-src': ["'self'", 'data:', 'https:'],
        'script-src': isProduction ? ["'strict-dynamic'", "'self'"] : ["'strict-dynamic'", "'unsafe-eval'", "'self'"],
        'script-src-attr': ["'none'"],
        'style-src': ["'self'"],
        'style-src-attr': ["'unsafe-inline'"],
        'upgrade-insecure-requests': isProduction ? [] : null,
      },
    },
  });
}
